import json
import os

# We will generate a rich, accurate dictionary with >1000 terms
entries = []
seen = set()

def add(en, es, cat, pos, pho_en, pho_es, def_es, ex_en, ex_es):
    key = en.lower().strip()
    if key in seen:
        return
    seen.add(key)
    id_str = "".join([c if c.isalnum() else "-" for c in key]).strip("-")
    entries.append({
        "id": id_str,
        "en": en.strip(),
        "es": es.strip(),
        "category": cat.strip(),
        "partOfSpeech": pos.strip(),
        "phoneticEn": pho_en.strip(),
        "phoneticEs": pho_es.strip(),
        "definitionEs": def_es.strip(),
        "exampleEn": ex_en.strip(),
        "exampleEs": ex_es.strip()
    })

# Domains with rich lists
tactical = [
    ("advance", "avanzar / avance", "Tactical & Combat", "verb & noun", "/ədˈvɑːns/", "ad-váns", "Movimiento coordinado hacia el frente.", "Platoons will advance at dusk.", "Las secciones avanzarán al anochecer."),
    ("ambush", "emboscada", "Tactical & Combat", "noun & verb", "/ˈæm.bʊʃ/", "ám-bush", "Ataque sorpresivo desde posición oculta.", "The squad set up a hasty ambush.", "La escuadra montó una emboscada improvisada."),
    ("assault", "asalto / asaltar", "Tactical & Combat", "noun & verb", "/əˈsɔːlt/", "a-sólt", "Fase culminante y violenta de un ataque.", "Infantry launched a frontal assault.", "La infantería lanzó un asalto frontal."),
    ("barrage", "fuego de barrera", "Tactical & Combat", "noun", "/ˈbær.ɑːʒ/", "bá-raash", "Fuego masivo continuo de artillería.", "Artillery barrage neutralized enemy batteries.", "El fuego de barrera artillero neutralizó las baterías enemigas."),
    ("battlefield", "campo de batalla", "Tactical & Combat", "noun", "/ˈbæt.əl.fiːld/", "bát-el-fild", "Zona donde se libra el combate.", "Medics evacuated casualties from the battlefield.", "Los enfermeros evacuaron bajas del campo de batalla."),
    ("beachhead", "cabeza de playa", "Tactical & Combat", "noun", "/ˈbiːtʃ.hed/", "bíich-jed", "Área costera asegurada tras desembarco.", "Marines expanded the beachhead.", "Los infantes de marina ampliaron la cabeza de playa."),
    ("blockade", "bloqueo", "Tactical & Combat", "noun & verb", "/blɒkˈeɪd/", "blok-éid", "Aislamiento para cortar suministros.", "A naval blockade isolated the hostile port.", "Un bloqueo naval aisló el puerto hostil."),
    ("breakthrough", "ruptura táctica", "Tactical & Combat", "noun", "/ˈbreɪk.θruː/", "bréik-zru", "Acción de quebrar líneas enemigas.", "Armoured units achieved a tactical breakthrough.", "Las unidades blindadas lograron una ruptura táctica."),
    ("bridgehead", "cabeza de puente", "Tactical & Combat", "noun", "/ˈbrɪdʒ.hed/", "brídch-jed", "Posición asegurada al otro lado de un río.", "Engineers protected the bridgehead.", "Los ingenieros protegieron la cabeza de puente."),
    ("casualty", "baja (militar)", "Tactical & Combat", "noun", "/ˈkæʒ.ju.əl.ti/", "kásh-ual-ti", "Militar muerto, herido o desaparecido.", "The unit reported zero casualties.", "La unidad reportó cero bajas."),
    ("ceasefire", "alto el fuego", "Tactical & Combat", "noun", "/ˈsiːs.faɪər/", "síis-fáier", "Suspensión acordada de los combates.", "A temporary ceasefire was declared at noon.", "Se declaró un alto el fuego temporal al mediodía."),
    ("checkpoint", "puesto de control", "Tactical & Combat", "noun", "/ˈtʃek.pɔɪnt/", "chék-point", "Punto fortificado de registro vehicular.", "Sentries inspected trucks at the checkpoint.", "Los centinelas inspeccionaron camiones en el puesto de control."),
    ("choke point", "punto de estrangulamiento", "Tactical & Combat", "noun", "/ˈtʃəʊk pɔɪnt/", "chóuk point", "Paso geográfico estrecho que canaliza tropas.", "The canyon formed a natural choke point.", "El cañón formaba un punto de estrangulamiento natural."),
    ("close air support", "apoyo aéreo cercano (CAS)", "Tactical & Combat", "noun", "/kləʊs eə səˈpɔːt/", "clóus éar sa-pórt", "Ataque aéreo cerca de tropas amigas.", "Jets provided timely close air support.", "Los aviones caza brindaron oportuno apoyo aéreo cercano."),
    ("combat patrol", "patrulla de combate", "Tactical & Combat", "noun", "/ˈkɒm.bæt pəˈtrəʊl/", "kóm-bat pa-tróul", "Patrulla con misión de combate o captura.", "The combat patrol secured the flank.", "La patrulla de combate aseguró el flanco."),
    ("combined arms", "armas combinadas", "Tactical & Combat", "noun", "/kəmˈbaɪnd ɑːmz/", "com-báind áarms", "Integración de infantería, tanques y artillería.", "Combined arms tactics broke the defense.", "Las tácticas de armas combinadas quebraron la defensa."),
    ("command post", "puesto de mando (CP)", "Tactical & Combat", "noun", "/kəˈmɑːnd pəʊst/", "ca-mánd póust", "Instalación táctica de mando y control.", "The commander remains at the tactical command post.", "El comandante permanece en el puesto de mando táctico."),
    ("concealment", "ocultamiento", "Tactical & Combat", "noun", "/kənˈsiːl.mənt/", "con-síil-ment", "Protección contra la vista del enemigo.", "Dense vegetation offers superior concealment.", "La densa vegetación ofrece excelente ocultamiento."),
    ("cover", "cubierta / cobertura", "Tactical & Combat", "noun & verb", "/ˈkʌv.ər/", "kóv-er", "Protección física contra el fuego balístico.", "Seek cover behind reinforced earthworks.", "Busque cubierta detrás de terraplenes reforzados."),
    ("counter-attack", "contraataque", "Tactical & Combat", "noun & verb", "/ˈkaʊn.tər.ə.tæk/", "káun-ter-aták", "Ataque para repeler o recuperar terreno.", "The battalion delivered a crushing counter-attack.", "El batallón propinó un aplastante contraataque."),
    ("cordon and search", "acordonamiento y registro", "Tactical & Combat", "noun", "/ˈkɔː.dən ənd sɜːtʃ/", "kóor-don and séerch", "Aislamiento y registro de una zona urbana.", "Troops executed a cordon and search drill.", "Las tropas ejecutaron un ejercicio de acordonamiento y registro."),
    ("defensive perimeter", "perímetro defensivo", "Tactical & Combat", "noun", "/dɪˈfen.sɪv pəˈrɪm.ɪ.tər/", "di-fén-siv pe-rím-eter", "Línea perimétrica de seguridad en 360°.", "Sentries patrolled the defensive perimeter.", "Los centinelas patrullaron el perímetro defensivo."),
    ("deploy", "desplegar", "Tactical & Combat", "verb", "/dɪˈplɔɪ/", "di-plói", "Posicionar unidades o armas en el terreno.", "The company deployed along the ridgeline.", "La compañía se desplegó a lo largo de la cresta."),
    ("deployment", "despliegue", "Tactical & Combat", "noun", "/dɪˈplɔɪ.mənt/", "di-plói-ment", "Traslado de tropas al teatro operativo.", "Overseas deployment lasts six months.", "El despliegue en el exterior dura seis meses."),
    ("direct fire", "tiro directo", "Tactical & Combat", "noun", "/daɪˈrekt ˈfaɪər/", "dai-rékt fáier", "Fuego apuntado directamente al blanco.", "Anti-tank guns opened direct fire.", "Los cañones contracarro abrieron tiro directo."),
    ("disengage", "romper el contacto", "Tactical & Combat", "verb", "/ˌdɪs.ɪŋˈɡeɪdʒ/", "dis-in-guéidch", "Interrumpir el combate y replegarse ordenadamente.", "The squad disengaged under heavy smoke.", "La escuadra rompió el contacto bajo denso humo."),
    ("dismounted", "desmontado / a pie", "Tactical & Combat", "adjective", "/dɪsˈmaʊn.tɪd/", "dis-máun-tid", "Tropas que operan a pie fuera de vehículos.", "Dismounted infantry swept the orchard.", "La infantería desmontada rastrilló el huerto."),
    ("drop zone", "zona de lanzamiento (DZ)", "Tactical & Combat", "noun", "/ˈdrɒp zəʊn/", "drop zóun", "Zona señalizada para caída de paracaidistas.", "Supplies landed safely on the drop zone.", "Los suministros cayeron a salvo en la zona de lanzamiento."),
    ("encirclement", "cerco militar", "Tactical & Combat", "noun", "/ɪnˈsɜː.kəl.mənt/", "in-séer-kel-ment", "Aislamiento total de una fuerza por el adversario.", "Units broke through the enemy encirclement.", "Las unidades rompieron a través del cerco enemigo."),
    ("engagement", "enfrentamiento armado", "Tactical & Combat", "noun", "/ɪnˈɡeɪdʒ.mənt/", "in-guéidch-ment", "Contacto de fuego entre tropas.", "The skirmish escalated into a major engagement.", "La escaramuza escaló a un enfrentamiento mayor."),
    ("evacuation", "evacuación", "Tactical & Combat", "noun", "/ɪˌvæk.juˈeɪ.ʃən/", "i-vak-iu-éishon", "Traslado de heridos o personal a zona segura.", "Helicopter evacuation was requested immediately.", "Se solicitó evacuación en helicóptero inmediatamente."),
    ("extraction", "extracción", "Tactical & Combat", "noun", "/ɪkˈstræk.ʃən/", "eks-trák-shon", "Retirada planeada de fuerzas de territorio hostil.", "The extraction team arrived at the LZ.", "El equipo de extracción llegó a la zona de aterrizaje."),
    ("fire and movement", "fuego y maniobra", "Tactical & Combat", "noun", "/faɪər ənd ˈmuːv.mənt/", "fáier and múuv-ment", "Técnica táctica básica de avance protegido.", "Practice fire and movement across open fields.", "Practiquen fuego y maniobra a través de campos abiertos."),
    ("fire support", "apoyo de fuegos", "Tactical & Combat", "noun", "/ˈfaɪə səˌpɔːt/", "fáier sa-pórt", "Fuegos artilleros o aéreos para apoyar la maniobra.", "Mortars provided effective fire support.", "Los morteros brindaron eficaz apoyo de fuegos."),
    ("flank", "flanco", "Tactical & Combat", "noun & verb", "/flæŋk/", "flank", "Costado derecho o izquierdo de una formación.", "Securing the eastern flank is top priority.", "Asegurar el flanco este es máxima prioridad."),
    ("forward operating base", "base de operaciones avanzada (FOB)", "Tactical & Combat", "noun", "/ˈfɔː.wəd ˈɒp.ər.eɪ.tɪŋ beɪs/", "fór-uerd op-er-éiting béis", "Base segura adelantada cercana al frente.", "Fuel tankers reached the forward operating base.", "Los camiones cisterna llegaron a la base avanzada."),
    ("friendly fire", "fuego amigo", "Tactical & Combat", "noun", "/ˈfrend.li ˈfaɪər/", "frénd-li fáier", "Fuego involuntario contra tropas propias.", "Clear markings help eliminate friendly fire.", "Las marcas claras ayudan a eliminar el fuego amigo."),
    ("harassment", "hostigamiento", "Tactical & Combat", "noun", "/ˈhær.əs.mənt/", "jár-as-ment", "Fuego esporádico para desgastar al enemigo.", "Sniper harassment interrupted enemy supply lines.", "El hostigamiento de francotiradores interrumpió las líneas enemigas."),
    ("incursion", "incursión", "Tactical & Combat", "noun", "/ɪnˈkɜː.ʃən/", "in-kér-shon", "Entrada militar rápida y temporal en territorio rival.", "Border patrols repulsed an armed incursion.", "Las patrullas fronterizas rechazaron una incursión armada."),
    ("indirect fire", "tiro indirecto", "Tactical & Combat", "noun", "/ˌɪn.daɪˈrekt ˈfaɪər/", "in-dai-rékt fáier", "Tiro sobre blancos no visibles (artillería).", "Howitzers fired indirect fire onto grid coordinates.", "Los obuses dispararon tiro indirecto a coordenadas de cuadrícula."),
    ("infiltration", "infiltración", "Tactical & Combat", "noun", "/ˌɪn.fɪlˈtreɪ.ʃən/", "in-fil-tréishon", "Paso furtivo a través de líneas enemigas.", "The squad completed infiltration undetected.", "La escuadra completó la infiltración sin ser detectada."),
    ("landing zone", "zona de aterrizaje (LZ)", "Tactical & Combat", "noun", "/ˈlæn.dɪŋ zəʊn/", "lán-ding zóun", "Área para posarse helicópteros.", "Green smoke marked the landing zone.", "Humo verde marcó la zona de aterrizaje."),
    ("manoeuvre", "maniobra", "Tactical & Combat", "noun & verb", "/məˈnuː.vər/", "ma-núu-ver", "Desplazamiento para ganar ventaja posicional.", "Rapid manoeuvre surprised enemy reserves.", "La rápida maniobra sorprendió a las reservas enemigas."),
    ("neutralize", "neutralizar", "Tactical & Combat", "verb", "/ˈnjuː.trə.laɪz/", "niúu-tra-lais", "Inutilizar o destruir una amenaza militar.", "Our airstrike neutralized the radar site.", "Nuestro ataque aéreo neutralizó el sitio de radar."),
    ("objective", "objetivo militar", "Tactical & Combat", "noun", "/əbˈdʒek.tɪv/", "ob-dchék-tiv", "Lugar o blanco asignado para conquistar.", "Alpha Company secured Objective Red.", "La Compañía Alfa aseguró el Objetivo Rojo."),
    ("observation post", "puesto de observación (OP)", "Tactical & Combat", "noun", "/ˌɒb.zəˈveɪ.ʃən pəʊst/", "ob-zer-véishon póust", "Puesto avanzado para vigilar al enemigo.", "Scouts reported from the observation post.", "Los exploradores reportaron desde el puesto de observación."),
    ("offensive", "ofensiva", "Tactical & Combat", "noun & adjective", "/əˈfen.sɪv/", "o-fén-siv", "Ataque coordinado en gran escala.", "The army initiated a spring offensive.", "El ejército inició una ofensiva de primavera."),
    ("perimeter defense", "defensa perimétrica", "Tactical & Combat", "noun", "/pəˈrɪm.ɪ.tər dɪˈfens/", "pe-rím-eter di-féns", "Disposición defensiva circular completa.", "Establish perimeter defense before dark.", "Establezcan defensa perimétrica antes de que oscurezca."),
    ("pincer movement", "movimiento de pinza", "Tactical & Combat", "noun", "/ˈpɪn.sər ˈmuːv.mənt/", "pín-ser múuv-ment", "Ataque convergente sobre ambos flancos.", "The regiment executed a classic pincer movement.", "El regimiento ejecutó un clásico movimiento de pinza."),
    ("raid", "golpe de mano", "Tactical & Combat", "noun & verb", "/reɪd/", "réid", "Ataque sorpresivo con repliegue veloz.", "Commandos launched a night raid on the depot.", "Los comandos lanzaron un golpe de mano nocturno en el depósito."),
    ("readiness", "alistamiento", "Tactical & Combat", "noun", "/ˈred.i.nəs/", "réd-i-nes", "Estado de preparación para el combate.", "The battalion is in high combat readiness.", "El batallón está en alto alistamiento para el combate."),
    ("reconnaissance", "reconocimiento", "Tactical & Combat", "noun", "/rɪˈkɒn.ɪ.səns/", "ri-kón-i-sens", "Exploración del terreno y del enemigo.", "Reconnaissance patrols mapped enemy trenches.", "Las patrullas de reconocimiento mapearon las trincheras enemigas."),
    ("reinforcement", "refuerzo", "Tactical & Combat", "noun", "/ˌriː.ɪnˈfɔːs.mənt/", "rii-in-fóors-ment", "Tropas enviadas para fortalecer una posición.", "Send reinforcements to Sector Bravo immediately.", "Envíen refuerzos al Sector Bravo inmediatamente."),
    ("retreat", "retirada", "Tactical & Combat", "noun & verb", "/rɪˈtriːt/", "ri-tríit", "Repliegue de tropas ante el enemigo.", "The enemy forces beat a hasty retreat.", "Las fuerzas enemigas emprendieron una apresurada retirada."),
    ("salient", "saliente táctico", "Tactical & Combat", "noun", "/ˈseɪ.li.ənt/", "séi-li-ent", "Parte del frente que penetra en líneas rivales.", "Our guns pounded the enemy salient.", "Nuestros cañones batieron el saliente enemigo."),
    ("sector", "sector militar", "Tactical & Combat", "noun", "/ˈsek.tər/", "sék-tor", "Zona asignada a una unidad militar.", "Hold sector 4 at all costs.", "Mantengan el sector 4 a toda costa."),
    ("siege", "sitio / asedio", "Tactical & Combat", "noun", "/siːdʒ/", "síidch", "Cerco prolongado a una fortaleza o ciudad.", "The siege lasted over forty days.", "El asedio duró más de cuarenta días."),
    ("skirmish", "escaramuza", "Tactical & Combat", "noun & verb", "/ˈskɜː.mɪʃ/", "skér-mish", "Combate menor entre pequeñas patrullas.", "Outposts engaged in a brief skirmish.", "Los puestos avanzados trabaron una breve escaramuza."),
    ("smoke screen", "cortina de humo", "Tactical & Combat", "noun", "/ˈsməʊk skriːn/", "smóuk skriin", "Humo para ocultar tropas en movimiento.", "Deploy smoke screens before crossing the bridge.", "Desplieguen cortinas de humo antes de cruzar el puente."),
    ("sniper", "francotirador", "Tactical & Combat", "noun", "/ˈsnaɪ.pər/", "snái-per", "Tirador selecto de precisión a distancia.", "The sniper pinned down hostile gunners.", "El francotirador aferró a los tiradores hostiles."),
    ("spearhead", "punta de lanza", "Tactical & Combat", "noun & verb", "/ˈspɪə.hed/", "spíer-jed", "Fuerza que lidera un asalto ofensivo.", "The tank regiment spearheads the push.", "El regimiento de tanques lidera el avance."),
    ("strongpoint", "punto fuerte", "Tactical & Combat", "noun", "/ˈstrɒŋ.pɔɪnt/", "stróng-point", "Posición defensiva fuertemente fortificada.", "Artillery pounded the concrete strongpoint.", "La artillería machacó el punto fuerte de hormigón."),
    ("suppressive fire", "fuego de supresión", "Tactical & Combat", "noun", "/səˈpres.ɪv ˈfaɪər/", "sa-prés-iv fáier", "Fuego para impedir que el enemigo responda.", "Lay down suppressive fire on those windows!", "¡Abran fuego de supresión sobre esas ventanas!"),
    ("surrender", "rendición / rendirse", "Tactical & Combat", "noun & verb", "/səˈren.dər/", "sa-rén-der", "Deponer las armas formalmente.", "The isolated garrison offered unconditional surrender.", "La guarnición aislada ofreció su rendición incondicional."),
    ("tactical withdrawal", "retirada táctica", "Tactical & Combat", "noun", "/ˈtæk.tɪ.kəl wɪðˈdrɔː.əl/", "ták-ti-kal uiz-dró-al", "Repliegue organizado para evitar pérdidas.", "The company carried out a tactical withdrawal.", "La compañía llevó a cabo una retirada táctica."),
    ("trench", "trinchera", "Tactical & Combat", "noun", "/trentʃ/", "trench", "Zanja excavada como protección defensiva.", "Infantry fortified the forward trench network.", "La infantería fortificó la red avanzada de trincheras."),
    ("urban warfare", "combate urbano (MOUT)", "Tactical & Combat", "noun", "/ˈɜː.bən ˈwɔː.feər/", "éer-ban uór-féar", "Lucha militar en calles y edificios.", "Urban warfare demands intense house-clearing skills.", "El combate urbano demanda destrezas de despeje de casas."),
    ("vanguard", "vanguardia", "Tactical & Combat", "noun", "/ˈvæn.ɡɑːd/", "ván-gard", "Parte delantera de un cuerpo de tropas.", "The scout vanguard crossed the border at 0400.", "La vanguardia de exploración cruzó la frontera a las 0400."),
    ("rear guard", "retaguardia", "Tactical & Combat", "noun", "/rɪə ɡɑːd/", "ríer gard", "Elemento militar que protege la retirada.", "The rear guard held off enemy pursuers.", "La retaguardia contuvo a los perseguidores enemigos."),
    ("zero hour", "hora cero", "Tactical & Combat", "noun", "/ˈzɪə.rəʊ ˈaʊər/", "zí-rou áuer", "Momento señalado para el ataque.", "Zero hour is set for 0530.", "La hora cero está fijada para las 0530."),
    ("air superiority", "superioridad aérea", "Tactical & Combat", "noun", "/eə suːˌpɪə.riˈɒr.ə.ti/", "éar su-pi-ri-ór-iti", "Dominio del espacio aéreo por una fuerza.", "Air superiority protected ground columns.", "La superioridad aérea protegió las columnas terrestres."),
    ("airborne assault", "asalto aerotransportado", "Tactical & Combat", "noun", "/ˈeə.bɔːn əˈsɔːlt/", "éar-boorn a-sólt", "Ataque ejecutado con paracaidistas.", "The airborne assault seized the vital airport.", "El asalto aerotransportado tomó el aeropuerto vital."),
    ("anti-tank ditch", "zanja antitanque", "Tactical & Combat", "noun", "/ˌæn.tiˈtæŋk dɪtʃ/", "án-ti-tank ditch", "Obstáculo excavado para detener blindados.", "Engineers breached the anti-tank ditch.", "Los zapadores abrieron brecha en la zanja antitanque."),
    ("area of operations", "área de operaciones (AO)", "Tactical & Combat", "noun", "/ˈeə.ri.ə əv ˌɒp.ərˈeɪ.ʃənz/", "é-ria ov op-er-éishons", "Zona geográfica asignada a un mando militar.", "The brigade cleared its designated area of operations.", "La brigada despejó su área de operaciones designada."),
    ("assault course", "pista de obstáculos / asalto", "Tactical & Combat", "noun", "/əˈsɔːlt kɔːs/", "a-sólt koors", "Circuito de adiestramiento físico militar.", "Recruits ran the assault course in full gear.", "Los reclutas recorrieron la pista de asalto con equipo completo."),
    ("bivouac", "vivac / acantonamiento", "Tactical & Combat", "noun & verb", "/ˈbɪv.u.æk/", "bív-u-ak", "Campamento improvisado al aire libre.", "Troops set up a bivouac in the pine woods.", "Las tropas montaron un vivac en el pinar."),
    ("body armor", "chaleco antibalas / blindaje personal", "Tactical & Combat", "noun", "/ˈbɒd.i ˌɑː.mər/", "bód-i áar-mor", "Protección balística corporal.", "Wear body armor and ballistic helmets at all times.", "Lleven chaleco antibalas y casco balístico en todo momento."),
    ("booby trap", "caza-bobos / trampa explosiva", "Tactical & Combat", "noun & verb", "/ˈbuː.bi træp/", "búu-bi trap", "Dispositivo explosivo disimulado.", "Engineers disarmed an explosive booby trap.", "Los zapadores desactivaron una trampa explosiva."),
    ("clearing operation", "operación de rastrillaje / despeje", "Tactical & Combat", "noun", "/ˈklɪə.rɪŋ ˌɒp.ərˈeɪ.ʃən/", "clíer-ing op-er-éishon", "Eliminación sistemática de amenazas en una zona.", "The squad carried out a building clearing operation.", "La escuadra ejecutó una operación de despeje de edificio."),
    ("collateral damage", "daño colateral", "Tactical & Combat", "noun", "/kəˈlæt.ər.əl ˈdæm.ɪdʒ/", "co-lát-er-al dám-idch", "Daño no intencionado a civiles o bienes.", "Precision-guided munitions minimize collateral damage.", "Las municiones guiadas de precisión minimizan el daño colateral."),
    ("combat engineer", "ingeniero de combate / zapador", "Tactical & Combat", "noun", "/ˈkɒm.bæt ˌen.dʒɪˈnɪər/", "kóm-bat en-dchi-níer", "Soldado especializado en puentes, minas y obras.", "Combat engineers cleared a safe path through the minefield.", "Los zapadores despejaron un paso seguro por el campo minado."),
    ("combat readiness", "alistamiento para el combate", "Tactical & Combat", "noun", "/ˈkɒm.bæt ˈred.i.nəs/", "kóm-bat réd-i-nes", "Grado de preparación de una fuerza militar.", "The brigade maintains high combat readiness.", "La brigada mantiene un alto alistamiento para el combate."),
    ("command and control", "mando y control (C2)", "Tactical & Combat", "noun", "/kəˈmɑːnd ənd kənˈtrəʊl/", "ca-mánd and con-tróul", "Ejercicio de autoridad y dirección militar.", "Secure satellite links ensure robust command and control.", "Los enlaces satelitales seguros aseguran un mando y control robusto."),
    ("contact report", "informe de contacto", "Tactical & Combat", "noun", "/ˈkɒn.tækt rɪˈpɔːt/", "kón-takt ri-póort", "Transmisión radial inmediata al trabar combate.", "Radio operator transmitted an urgent contact report.", "El radiooperador transmitió un informe de contacto urgente."),
    ("counter-battery fire", "fuego de contrabatería", "Tactical & Combat", "noun", "/ˈkaʊn.tər ˈbæt.ər.i faɪər/", "káun-ter bát-er-i fáier", "Fuego de artillería para destruir cañones enemigos.", "Radar data guided swift counter-battery fire.", "Los datos de radar guiaron un rápido fuego de contrabatería."),
    ("dead ground", "ángulo muerto / terreno desenfilado", "Tactical & Combat", "noun", "/ded ɡraʊnd/", "ded gráund", "Terreno que no puede batirse desde una posición.", "Enemy scouts took shelter in the dead ground.", "Los exploradores enemigos se refugiaron en el ángulo muerto."),
    ("defilade", "desenfilada", "Tactical & Combat", "noun", "/ˈdef.ɪ.leɪd/", "déf-i-leid", "Posición a cubierto del fuego y vista enemiga.", "Tanks fired from turret-down defilade.", "Los tanques dispararon desde desenfilada de torreta."),
    ("demolition charge", "carga de demolición", "Tactical & Combat", "noun", "/ˌdem.əˈlɪʃ.ən tʃɑːdʒ/", "dem-o-líshon cháardch", "Explosivo para destruir puentes o fortificaciones.", "Engineers placed demolition charges on the pier.", "Los zapadores colocaron cargas de demolición en el muelle."),
    ("disposition", "dispositivo / orden de batalla", "Tactical & Combat", "noun", "/ˌdɪs.pəˈzɪʃ.ən/", "dis-po-zíshon", "Distribución de tropas y armas en el terreno.", "Study enemy defensive dispositions carefully.", "Estudien atentamente el dispositivo defensivo enemigo."),
    ("dugout", "abrigo excavado", "Tactical & Combat", "noun", "/ˈdʌɡ.aʊt/", "dág-aut", "Refugio subterráneo protegido contra bombas.", "Troops sheltered inside the reinforced dugout.", "Las tropas se guarecieron en el abrigo excavado reforzado."),
    ("electronic warfare", "guerra electrónica (EW)", "Tactical & Combat", "noun", "/ɪˌlek.trɒn.ɪk ˈwɔː.feər/", "i-lec-trón-ik uór-féar", "Uso de energía electromagnética para anular señales.", "Electronic warfare units jammed hostile radios.", "Unidades de guerra electrónica interfirieron las radios hostiles."),
    ("embankment", "terraplén", "Tactical & Combat", "noun", "/ɪmˈbæŋk.mənt/", "im-bánk-ment", "Muro de tierra levantado para defensa o vía férrea.", "Troops took cover behind the railroad embankment.", "Las tropas se cubrieron detrás del terraplén del ferrocarril."),
    ("enfilade fire", "fuego de enfilada", "Tactical & Combat", "noun", "/ˈen.fɪ.leɪd faɪər/", "én-fi-leid fáier", "Fuego dirigido a lo largo de la línea enemiga.", "Machine guns caught the trench in devastating enfilade fire.", "Las ametralladoras batieron la trinchera con devastador fuego de enfilada."),
    ("forward edge of battle area", "borde delantero del área de combate (FEBA)", "Tactical & Combat", "noun", "/ˈfɔː.wəd edʒ əv ˈbæt.əl ˈeə.ri.ə/", "fór-uerd edch ov bát-el é-ria", "Línea más avanzada de las defensas terrestres.", "The FEBA was heavily mined and fortified.", "El FEBA estaba intensamente minado y fortificado."),
    ("foxhole", "pozo de tirador", "Tactical & Combat", "noun", "/ˈfɒks.həʊl/", "fóks-joul", "Hoyo excavado para un combatiente.", "Dig a deep foxhole with overhead cover.", "Cave un pozo de tirador profundo con techo de protección."),
    ("grenade launcher", "lanzagranadas", "Tactical & Combat", "noun", "/ɡrəˈneɪd ˌlɔːn.tʃər/", "gre-néid lóon-cher", "Arma para disparar granadas a distancia.", "The under-barrel grenade launcher engaged the bunker.", "El lanzagranadas acoplado batió el búnker."),
    ("interdiction", "interdicción", "Tactical & Combat", "noun", "/ˌɪn.təˈdɪk.ʃən/", "in-ter-dík-shon", "Ataques para cortar rutas y suministros rivales.", "Air interdiction severed the enemy rail junction.", "La interdicción aérea cortó el nudo ferroviario enemigo."),
    ("kill zone", "zona de aniquilamiento", "Tactical & Combat", "noun", "/ˈkɪl zəʊn/", "kil zóun", "Área batida por fuego cruzado concentrado.", "The ambush trapped the vehicle column in the kill zone.", "La emboscada atrapó a la columna de vehículos en la zona de aniquilamiento."),
    ("line of departure", "línea de partida (LD)", "Tactical & Combat", "noun", "/laɪn əv dɪˈpɑː.tʃər/", "láin ov di-páar-cher", "Línea designada para coordinar el inicio del ataque.", "Units crossed the line of departure at 0600 sharp.", "Las unidades cruzaron la línea de partida a las 0600 en punto."),
    ("minefield", "campo minado", "Tactical & Combat", "noun", "/ˈmaɪn.fiːld/", "máin-fild", "Área sembrada de minas terrestres.", "Signs marked the perimeter of an active minefield.", "Carteles marcaban el perímetro de un campo minado activo."),
    ("night-vision goggles", "gafas de visión nocturna (NVG)", "Tactical & Combat", "noun", "/naɪt ˈvɪʒ.ən ˈɡɒɡ.əlz/", "náit-víshon góg-els", "Dispositivo óptico para ver en la oscuridad.", "Soldiers navigated through the dark with night-vision goggles.", "Los soldados se desplazaron en la oscuridad con gafas de visión nocturna."),
    ("no-man's land", "tierra de nadie", "Tactical & Combat", "noun", "/ˌnəʊ.mænz ˈlænd/", "nóu-mans lánd", "Espacio no dominado entre líneas enemigas.", "Patrols crossed no-man's land under starless skies.", "Las patrullas cruzaron la tierra de nadie bajo cielos sin estrellas."),
    ("reconnaissance by fire", "reconocimiento por el fuego", "Tactical & Combat", "noun", "/rɪˈkɒn.ɪ.səns baɪ faɪər/", "ri-kón-i-sens bai fáier", "Disparar a posiciones dudosas para forzar respuesta enemiga.", "The platoon conducted reconnaissance by fire into the treeline.", "La sección efectuó reconocimiento por el fuego hacia el linde del bosque."),
    ("rules of engagement", "reglas de enfrentamiento (ROE)", "Tactical & Combat", "noun", "/ruːlz əv ɪnˈɡeɪdʒ.mənt/", "ruuls ov in-guéidch-ment", "Directivas que regulan el empleo de la fuerza.", "Review the rules of engagement before mounting the patrol.", "Repasen las reglas de enfrentamiento antes de montar la patrulla."),
    ("standoff distance", "distancia de seguridad / alcance útil", "Tactical & Combat", "noun", "/ˈstænd.ɒf ˈdɪs.təns/", "stánd-of dís-tans", "Distancia que permite atacar fuera del alcance enemigo.", "Drones struck targets from safe standoff distance.", "Los drones batieron blancos desde distancia de seguridad.")
]

weapons = [
    ("assault rifle", "fusil de asalto", "Weapons & Ballistics", "noun", "/əˈsɔːlt ˈraɪ.fəl/", "a-sólt rái-fl", "Fusil militar automático y semiautomático.", "Soldiers cleaned their assault rifles before inspection.", "Los soldados limpiaron sus fusiles de asalto antes de la revista."),
    ("submachine gun", "subfusil / pistola ametralladora", "Weapons & Ballistics", "noun", "/ˌsʌb.məˈʃiːn ɡʌn/", "sab-ma-shíin gan", "Arma automática ligera de calibre de pistola.", "The bodyguard carried a compact submachine gun.", "El escolta portaba un subfusil compacto."),
    ("pistol", "pistola", "Weapons & Ballistics", "noun", "/ˈpɪs.təl/", "pís-tl", "Arma de fuego corta para defensa personal.", "Officers carry a standard nine-millimetre pistol.", "Los oficiales portan una pistola reglamentaria de nueve milímetros."),
    ("revolver", "revólver", "Weapons & Ballistics", "noun", "/rɪˈvɒl.vər/", "ri-vól-ver", "Arma corta con tambor giratorio para cartuchos.", "The sentry had an antique service revolver.", "El centinela tenía un antiguo revólver de servicio."),
    ("machine gun", "ametralladora", "Weapons & Ballistics", "noun", "/məˈʃiːn ɡʌn/", "ma-shíin gan", "Arma de tiro automático continuo con cinta o cargador.", "The squad machine gun covered the main avenue.", "La ametralladora de escuadra cubrió la avenida principal."),
    ("heavy machine gun", "ametralladora pesada", "Weapons & Ballistics", "noun", "/ˌhev.i məˈʃiːn ɡʌn/", "jév-i ma-shíin gan", "Ametralladora de calibre 12.7 mm montada en afuste.", "A heavy machine gun was mounted on the armoured vehicle.", "Se montó una ametralladora pesada en el vehículo blindado."),
    ("sniper rifle", "fusil de precisión / francotirador", "Weapons & Ballistics", "noun", "/ˈsnaɪ.pər ˈraɪ.fəl/", "snái-per rái-fl", "Fusil de alta precisión dotado de mira telescópica.", "The sniper rifle was zeroed at eight hundred metres.", "El fusil de precisión fue calibrado a ochocientos metros."),
    ("carbine", "carabina", "Weapons & Ballistics", "noun", "/ˈkɑː.biːn/", "cáar-bain", "Fusil con cañón corto y culata plegable.", "Vehicle crews are equipped with compact carbines.", "Las dotaciones de vehículos están equipadas con carabinas compactas."),
    ("shotgun", "escopeta", "Weapons & Ballistics", "noun", "/ˈʃɒt.ɡʌn/", "shót-gan", "Arma de fuego para cartuchos de perdigones o postas.", "Breaching teams use 12-gauge shotguns for door hinges.", "Los equipos de brecha usan escopetas calibre 12 para bisagras de puertas."),
    ("mortar", "mortero", "Weapons & Ballistics", "noun", "/ˈmɔː.tər/", "móor-tar", "Arma de tiro curvo para proyectiles explosivos.", "The 81 mm mortar crew fired three rounds.", "La dotación del mortero de 81 mm disparó tres proyectiles."),
    ("howitzer", "obús", "Weapons & Ballistics", "noun", "/ˈhaʊ.ɪt.sər/", "jáu-it-ser", "Pieza de artillería para tiro directo o indirecto.", "The 155 mm howitzer provided long-range fire.", "El obús de 155 mm proporcionó fuego de largo alcance."),
    ("rocket launcher", "lanzacohetes", "Weapons & Ballistics", "noun", "/ˈrɒk.ɪt ˌlɔːn.tʃər/", "rók-it lóon-cher", "Tubo portátil para disparar cohetes antitanque.", "The grenadier aimed the rocket launcher at the bunker.", "El granadero apuntó el lanzacohetes hacia el búnker."),
    ("anti-tank missile", "misil antitanque (ATGM)", "Weapons & Ballistics", "noun", "/ˌæn.tiˈtæŋk ˈmɪs.aɪl/", "án-ti-tank mís-ail", "Misil guiado diseñado para destruir blindados.", "The anti-tank missile destroyed the hostile tank at 3 km.", "El misil antitanque destruyó el blindado enemigo a 3 km."),
    ("surface-to-air missile", "misil superficie-aire (SAM)", "Weapons & Ballistics", "noun", "/ˌsɜː.fɪs.tuˈeər ˈmɪs.aɪl/", "séer-fis-tu-éar mís-ail", "Misil lanzado desde tierra contra aeronaves.", "Air defense batteries fired a surface-to-air missile.", "Las baterías de defensa aérea dispararon un misil superficie-aire."),
    ("anti-aircraft gun", "cañón antiaéreo", "Weapons & Ballistics", "noun", "/ˌæn.tiˈeə.krɑːft ɡʌn/", "án-ti-éar-kraft gan", "Cañón automático para abatir aeronaves.", "Twin anti-aircraft guns guarded the bridge.", "Cañones antiaéreos dobles custodiaban el puente."),
    ("main battle tank", "carro de combate principal (MBT)", "Weapons & Ballistics", "noun", "/meɪn ˈbæt.əl tæŋk/", "méin bát-el tank", "Vehículo blindado pesado con cañón de alta potencia.", "The main battle tank advanced with infantry support.", "El carro de combate principal avanzó con apoyo de infantería."),
    ("armoured personnel carrier", "transporte blindado de personal (APC)", "Weapons & Ballistics", "noun", "/ˌɑː.məd ˌpɜː.sənˈel ˌkær.i.ər/", "áar-mod per-so-nél cá-rier", "Blindado para transportar infantes seguros al combate.", "Troops dismounted from the armoured personnel carrier.", "Las tropas desmontaron del transporte blindado de personal."),
    ("infantry fighting vehicle", "vehículo de combate de infantería (IFV)", "Weapons & Ballistics", "noun", "/ˈɪn.fən.tri ˈfaɪ.tɪŋ ˌviː.ɪ.kəl/", "ín-fan-tri fái-ting ví-ikl", "Blindado armado con cañón automático que transporta tropas.", "The infantry fighting vehicle engaged with its autocannon.", "El vehículo de combate de infantería batió con su cañón automático."),
    ("reconnaissance vehicle", "vehículo de reconocimiento", "Weapons & Ballistics", "noun", "/rɪˈkɒn.ɪ.səns ˌviː.ɪ.kəl/", "ri-kón-i-sens ví-ikl", "Vehículo ligero y veloz para explorar terreno.", "Light reconnaissance vehicles scouted the valley ahead.", "Vehículos ligeros de reconocimiento exploraron el valle adelante."),
    ("self-propelled artillery", "artillería autopropulsada", "Weapons & Ballistics", "noun", "/ˌself.prəˈpeld ɑːˈtɪl.ər.i/", "self-pro-péld aar-tíl-eri", "Pieza artillera montada sobre chasis de orugas o ruedas.", "Self-propelled artillery changed positions after firing.", "La artillería autopropulsada cambió de posición tras disparar."),
    ("unmanned aerial vehicle", "vehículo aéreo no tripulado (UAV / Dron)", "Weapons & Ballistics", "noun", "/ʌnˌmænd ˈeə.ri.əl ˌviː.ɪ.kəl/", "an-mánd é-rial ví-ikl", "Aeronave guiada por control remoto o autónoma.", "An unmanned aerial vehicle monitored enemy lines.", "Un vehículo aéreo no tripulado monitoreó las líneas enemigas."),
    ("loitering munition", "munición merodeadora / dron kamikaze", "Weapons & Ballistics", "noun", "/ˈlɔɪ.tər.ɪŋ mjuːˈnɪʃ.ən/", "lói-ter-ing miu-níshon", "Dron explosivo que busca y ataca blancos.", "The loitering munition struck the command radar.", "La munición merodeadora atacó el radar de mando."),
    ("ammunition", "munición", "Weapons & Ballistics", "noun", "/ˌæm.jəˈnɪʃ.ən/", "am-iu-níshon", "Cartuchos, proyectiles y cargas para armas.", "Check your ammunition levels before the mission.", "Comprueben sus niveles de munición antes de la misión."),
    ("cartridge", "cartucho", "Weapons & Ballistics", "noun", "/ˈkɑː.trɪdʒ/", "cáar-tridch", "Unidad completa de vaina, fulminante, pólvora y proyectil.", "Load 30 cartridges into the magazine.", "Carguen 30 cartuchos en el cargador."),
    ("magazine", "cargador (de munición)", "Weapons & Ballistics", "noun", "/ˌmæɡ.əˈziːn/", "mag-a-zíin", "Depósito extraíble que alimenta cartuchos al arma.", "Empty magazines must be retained in the dump pouch.", "Los cargadores vacíos deben guardarse en la bolsa de descarga."),
    ("bullet", "bala / proyectil", "Weapons & Ballistics", "noun", "/ˈbʊl.ɪt/", "búl-it", "Parte del cartucho que sale disparada por el cañón.", "The ceramic plate stopped the incoming bullet.", "La placa cerámica detuvo la bala entrante."),
    ("caliber", "calibre", "Weapons & Ballistics", "noun", "/ˈkæl.ɪ.bər/", "cál-i-ber", "Diámetro interno del cañón o del proyectil.", "The rifle uses 5.56 mm caliber ammunition.", "El fusil utiliza munición de calibre 5,56 mm."),
    ("barrel", "cañón (de arma)", "Weapons & Ballistics", "noun", "/ˈbær.əl/", "bá-rel", "Tubo metálico por donde sale el proyectil.", "Clean the rifle barrel with a bore snake.", "Limpie el cañón del fusil con una baqueta flexible."),
    ("breech", "recámara / cerrojo", "Weapons & Ballistics", "noun", "/briːtʃ/", "bríich", "Parte trasera del cañón donde se aloja el cartucho.", "Inspect the breech for carbon fouling.", "Inspeccione la recámara en busca de suciedad de pólvora."),
    ("firing pin", "percutor / aguja percutora", "Weapons & Ballistics", "noun", "/ˈfaɪə.rɪŋ pɪn/", "fáier-ing pin", "Pieza metálica que golpea el fulminante del cartucho.", "The armorer replaced the broken firing pin.", "El armero sustituyó la aguja percutora rota."),
    ("trigger", "gatillo / disparador", "Weapons & Ballistics", "noun", "/ˈtrɪɡ.ər/", "tríg-er", "Palanca que se presiona con el dedo para disparar.", "Keep your finger off the trigger until ready to fire.", "Mantenga el dedo fuera del disparador hasta disparar."),
    ("safety catch", "seguro (del arma)", "Weapons & Ballistics", "noun", "/ˈseɪf.ti kætʃ/", "séif-ti kach", "Mecanismo que impide el disparo accidental.", "Verify that your weapon is on safe.", "Verifique que su arma esté con el seguro puesto."),
    ("buttstock", "culata (de arma)", "Weapons & Ballistics", "noun", "/ˈbʌt.stɒk/", "bát-stok", "Parte posterior del fusil que se apoya en el hombro.", "Adjust the collapsible buttstock to your arm length.", "Ajuste la culata retráctil a la longitud de su brazo."),
    ("muzzle", "boca de fuego / de cañón", "Weapons & Ballistics", "noun", "/ˈmʌz.əl/", "máz-el", "Extremo frontal del cañón de un arma.", "Always keep the muzzle pointed in a safe direction.", "Mantenga siempre la boca del cañón apuntando en dirección segura."),
    ("muzzle brake", "freno de boca", "Weapons & Ballistics", "noun", "/ˈmʌz.əl breɪk/", "máz-el bréik", "Dispositivo para reducir el retroceso del disparo.", "The muzzle brake vents gases to reduce kickback.", "El freno de boca desvía los gases para reducir el retroceso."),
    ("recoil", "retroceso", "Weapons & Ballistics", "noun & verb", "/rɪˈkɔɪl/", "ri-cóil", "Fuerza hacia atrás producida al disparar.", "Firm stance absorbs the weapon recoil.", "Una postura firme absorbe el retroceso del arma."),
    ("rate of fire", "cadencia de tiro", "Weapons & Ballistics", "noun", "/reɪt əv faɪər/", "réit ov fáier", "Cantidad de disparos realizados por minuto.", "The machine gun has a rate of fire of 800 rounds/min.", "La ametralladora tiene una cadencia de 800 dpm."),
    ("effective range", "alcance eficaz", "Weapons & Ballistics", "noun", "/ɪˈfek.tɪv reɪndʒ/", "i-fék-tiv réindch", "Distancia máxima a la que un arma acierta con precisión.", "The assault rifle has an effective range of 400 metres.", "El fusil de asalto tiene un alcance eficaz de 400 metros."),
    ("maximum range", "alcance máximo", "Weapons & Ballistics", "noun", "/ˈmæk.sɪ.məm reɪndʒ/", "mák-si-mom réindch", "Distancia límite absoluta que alcanza un proyectil.", "The maximum range of the howitzer exceeds 30 kilometres.", "El alcance máximo del obús supera los 30 kilómetros."),
    ("trajectory", "trayectoria balística", "Weapons & Ballistics", "noun", "/trəˈdʒek.tər.i/", "tra-dchék-to-ri", "Curva que describe un proyectil en el aire.", "Wind and gravity alter the bullet trajectory.", "El viento y la gravedad alteran la trayectoria de la bala."),
    ("armor-piercing", "perforante de blindaje (AP)", "Weapons & Ballistics", "adjective", "/ˈɑː.mə ˌpɪə.sɪŋ/", "áar-mor píer-sing", "Proyectil endurecido para penetrar corazas.", "Crews loaded armor-piercing rounds against enemy tanks.", "Las dotaciones cargaron proyectiles perforantes contra blindados."),
    ("high-explosive", "alto explosivo (HE)", "Weapons & Ballistics", "adjective", "/ˌhaɪ.ɪkˈspləʊ.sɪv/", "jái-eks-plóu-siv", "Proyectil con carga explosiva para destrucción de área.", "High-explosive shells decimated the fortified trenches.", "Los proyectiles de alto explosivo diezmaron las trincheras."),
    ("tracer round", "proyectil trazador", "Weapons & Ballistics", "noun", "/ˈtreɪ.sər raʊnd/", "tréi-ser ráund", "Proyectil con fósforo que emite luz para corregir tiro.", "Every fifth round in the machine gun belt was a tracer.", "Uno de cada cinco proyectiles en la cinta era trazador."),
    ("shrapnel", "metralla / fragmentos", "Weapons & Ballistics", "noun", "/ˈʃræp.nəl/", "shráp-nel", "Fragmentos de metal proyectados por una explosión.", "Body armor protects vital organs from shell shrapnel.", "El chaleco balístico protege órganos vitales de la metralla."),
    ("hand grenade", "granada de mano", "Weapons & Ballistics", "noun", "/ˈhænd ɡrəˌneɪd/", "jánd gre-néid", "Artefacto explosivo arrojadizo personal.", "The soldier threw a hand grenade through the bunker slit.", "El soldado arrojó una granada de mano por la aspillera."),
    ("smoke grenade", "granada fumígena / de humo", "Weapons & Ballistics", "noun", "/ˈsməʊk ɡrəˌneɪd/", "smóuk gre-néid", "Granada que despide cortina de humo denso.", "Throw a smoke grenade to mask your movement.", "Arrojen una granada de humo para enmascarar su avance."),
    ("flashbang", "granada aturdidora (flashbang)", "Weapons & Ballistics", "noun", "/ˈflæʃ.bæŋ/", "flásh-bang", "Granada no letal de luz cegadora y fuerte estruendo.", "Breaching teams tossed a flashbang into the room.", "Los equipos de brecha lanzaron una aturdidora en la sala."),
    ("demining", "desminado", "Weapons & Ballistics", "noun", "/ˌdiːˈmaɪ.nɪŋ/", "dii-mái-ning", "Acción de localizar y desactivar minas terrestres.", "Humanitarian demining restored safety to rural farmland.", "El desminado humanitario devolvió la seguridad a los campos."),
    ("cluster munition", "munición de racimo", "Weapons & Ballistics", "noun", "/ˈklʌs.tər mjuːˌnɪʃ.ən/", "clás-ter miu-níshon", "Bomba que dispersa submuniciones explosivas.", "International treaties ban the use of cluster munitions.", "Tratados internacionales prohíben las municiones de racimo."),
    ("bayonet", "bayoneta", "Weapons & Ballistics", "noun", "/ˈbeɪ.ə.nət/", "béi-o-net", "Arma blanca que se acopla a la boca del fusil.", "Troops fixed bayonets before the final trench assault.", "Las tropas calaron bayonetas antes del asalto final.")
]

# Radio communications terms
radio = [
    ("roger", "entendido / comprendido (radio)", "Radio & Comms", "proword", "/ˈrɒdʒ.ər/", "ródch-er", "Mensaje recibido y comprendido totalmente.", "Roger that, moving to checkpoint Alpha.", "Entendido, avanzando hacia el puesto de control Alfa."),
    ("wilco", "comprendido y cumpliré (radio)", "Radio & Comms", "proword", "/ˈwɪl.kəʊ/", "uíl-cou", "Abreviatura de will comply: orden comprendida y en ejecución.", "Wilco, Bravo platoon is reinforcing now.", "Comprendido y en ejecución, sección Bravo reforzando ahora."),
    ("over", "cambio (terminé de hablar, espero respuesta)", "Radio & Comms", "proword", "/ˈəʊ.vər/", "óu-ver", "Fin de transmisión propia; paso al interlocutor.", "Eagle 6, this is Hawk 1, sitrep follows, over.", "Águila 6, aquí Halcón 1, sigue informe, cambio."),
    ("out", "cambio y fuera (fin de transmisión)", "Radio & Comms", "proword", "/aʊt/", "áut", "Fin de conversación; no se espera respuesta.", "Radio silence ordered until dawn, out.", "Silencio de radio ordenado hasta el amanecer, cambio y fuera."),
    ("say again", "repita (en comunicaciones militares)", "Radio & Comms", "proword", "/seɪ əˈɡen/", "séi a-guén", "Petición militar reglamentaria de repetir mensaje.", "Say again grid coordinates, signal degraded, over.", "Repita coordenadas, señal degradada, cambio."),
    ("standby", "espere / a la espera", "Radio & Comms", "proword", "/ˈstænd.baɪ/", "stánd-bai", "Petición de pausa momentánea en la transmisión.", "Standby, authenticating transmission.", "Espere, autenticando transmisión."),
    ("mayday", "mayday (socorro aéreo/marítimo)", "Radio & Comms", "proword", "/ˈmeɪ.deɪ/", "méi-dei", "Llamada internacional de emergencia extrema.", "Mayday, engine failure on inbound helicopter.", "Mayday, fallo de motor en helicóptero entrante."),
    ("pan-pan", "pan-pan (urgencia sin peligro inminente)", "Radio & Comms", "proword", "/pæn pæn/", "pan-pan", "Señal internacional de urgencia.", "Pan-pan, navigation system inoperative.", "Pan-pan, sistema de navegación inoperativo."),
    ("call sign", "indicativo de llamada (radio)", "Radio & Comms", "noun", "/ˈkɔːl saɪn/", "kóol sain", "Nombre en clave asignado a una estación o jefe.", "What is your call sign? This is Victor 2.", "¿Cuál es su indicativo? Aquí Víctor 2."),
    ("radio silence", "silencio de radio", "Radio & Comms", "noun", "/ˈreɪ.di.əʊ ˈsaɪ.ləns/", "réi-di-ou sái-lans", "Prohibición estricta de emitir señales de radio.", "Maintain absolute radio silence until crossing the river.", "Mantengan absoluto silencio de radio hasta cruzar el río."),
    ("frequency", "frecuencia de radio", "Radio & Comms", "noun", "/ˈfriː.kwən.si/", "fríi-kuen-si", "Canal de radio asignado para comunicaciones.", "Switch primary radios to emergency frequency 121.5.", "Cambien radios principales a la frecuencia de emergencia."),
    ("jamming", "interferencia electrónica intencionada", "Radio & Comms", "noun", "/ˈdʒæm.ɪŋ/", "dchám-ing", "Emisión deliberada de ruido para anular comunicaciones.", "Hostile jamming severed communications with HQ.", "Interferencia hostil cortó comunicaciones con el CG."),
    ("readability", "legibilidad de señal de radio", "Radio & Comms", "noun", "/ˌriː.dəˈbɪl.ə.ti/", "rii-da-bíl-iti", "Claridad con la que se escucha una transmisión.", "Signal strength five, readability five.", "Intensidad de señal cinco, legibilidad cinco."),
    ("sitrep", "informe de situación (sitrep)", "Radio & Comms", "noun", "/ˈsɪt.rep/", "sít-rep", "Resumen periódico de la situación táctica.", "All company commanders will submit a sitrep by 1800.", "Todos los jefes de compañía enviarán un sitrep a las 1800."),
    ("grid reference", "referencia de cuadrícula / coordenadas", "Radio & Comms", "noun", "/ɡrɪd ˈref.ər.əns/", "grid réf-er-ens", "Coordenadas numéricas de posición en la carta.", "Transmit grid reference of the downed drone.", "Transmita la referencia de cuadrícula del dron caído."),
    ("phonetic alphabet", "alfabeto fonético de la OTAN", "Radio & Comms", "noun", "/fəˈnet.ɪk ˈæl.fə.bet/", "fo-nét-ik ál-fa-bet", "Sistema alfa, bravo, charlie para deletrear palabras.", "Spell out vehicle license plates using the phonetic alphabet.", "Deletreen matrículas usando el alfabeto fonético."),
    ("encrypted", "cifrado / encriptado", "Radio & Comms", "adjective", "/ɪnˈkrɪp.tɪd/", "in-críp-tid", "Mensaje protegido mediante algoritmos de seguridad.", "Transmit only via encrypted frequency channels.", "Transmitan exclusivamente por canales cifrados."),
    ("antenna", "antena de comunicaciones", "Radio & Comms", "noun", "/ænˈten.ə/", "an-tén-a", "Dispositivo emisor y receptor de ondas de radio.", "Erect the whip antenna on high ground.", "Erijan la antena de látigo en terreno elevado."),
    ("transceiver", "transmisor-receptor / transceptor", "Radio & Comms", "noun", "/trænˈsiː.vər/", "tran-síi-ver", "Equipo que combina transmisor y receptor de radio.", "Check transceiver batteries before going on patrol.", "Comprueben las baterías del transceptor antes de patrullar."),
    ("repeater", "repetidor de señal", "Radio & Comms", "noun", "/rɪˈpiː.tər/", "ri-píi-ter", "Estación que retransmite señales para ampliar cobertura.", "The mountain repeater extends radio range by 50 miles.", "El repetidor de montaña amplía el alcance de radio 50 millas.")
]

# Ranks and military hierarchy
ranks = [
    ("private", "soldado raso", "Military Ranks & Hierarchy", "noun", "/ˈpraɪ.vət/", "prái-vat", "Soldado del escalón básico del ejército.", "Private Martinez stood guard at the main gate.", "El soldado Martínez montó guardia en la puerta principal."),
    ("corporal", "cabo", "Military Ranks & Hierarchy", "noun", "/ˈkɔː.pər.əl/", "kóor-po-ral", "Suboficial de menor graduación a cargo de escuadra.", "The corporal led his fire team across the clearing.", "El cabo lideró su equipo de fuego a través del claro."),
    ("sergeant", "sargento", "Military Ranks & Hierarchy", "noun", "/ˈsɑː.dʒənt/", "sáar-dchent", "Suboficial a cargo de una sección o pelotón.", "The sergeant inspected equipment readiness.", "El sargento inspeccionó el alistamiento del equipo."),
    ("staff sergeant", "sargento primero", "Military Ranks & Hierarchy", "noun", "/ˈstɑːf ˈsɑː.dʒənt/", "stáaf sáar-dchent", "Suboficial superior de la sección militar.", "The staff sergeant briefed squad leaders on the mission.", "El sargento primero instruyó a los jefes de escuadra."),
    ("master sergeant", "sargento ayudante / principal", "Military Ranks & Hierarchy", "noun", "/ˈmɑː.stə ˈsɑː.dʒənt/", "máas-ter sáar-dchent", "Suboficial de alta jerarquía técnica y operativa.", "The master sergeant supervises battalion maintenance.", "El sargento ayudante supervisa el mantenimiento del batallón."),
    ("sergeant major", "suboficial mayor", "Military Ranks & Hierarchy", "noun", "/ˌsɑː.dʒənt ˈmeɪ.dʒər/", "sáar-dchent méi-dchor", "El suboficial más antiguo del batallón o regimiento.", "The sergeant major enforced military discipline and drill.", "El suboficial mayor hizo cumplir la disciplina y el orden cerrado."),
    ("second lieutenant", "subteniente", "Military Ranks & Hierarchy", "noun", "/ˌsek.ənd lefˈten.ənt/", "sék-and lef-tén-ant", "Primer grado de la oficialidad al mando de sección.", "The second lieutenant reviewed terrain maps with the scout.", "El subteniente revisó cartas de terreno con el explorador."),
    ("first lieutenant", "teniente", "Military Ranks & Hierarchy", "noun", "/ˌfɜːst lefˈten.ənt/", "féerst lef-tén-ant", "Oficial al mando de una sección de combate.", "First lieutenant Perez coordinated indirect mortar fire.", "El teniente Pérez coordinó el fuego indirecto de mortero."),
    ("captain", "capitán", "Military Ranks & Hierarchy", "noun", "/ˈkæp.tɪn/", "káp-tin", "Oficial al mando de una compañía o batería.", "Captain Rogers commanded Bravo Company in battle.", "El capitán Rogers mandó la Compañía Bravo en combate."),
    ("major", "mayor", "Military Ranks & Hierarchy", "noun", "/ˈmeɪ.dʒər/", "méi-dchor", "Oficial jefe que suele actuar como segundo de batallón.", "The major served as battalion operations officer.", "El mayor se desempeñó como oficial de operaciones del batallón."),
    ("lieutenant colonel", "teniente coronel", "Military Ranks & Hierarchy", "noun", "/lefˌten.ənt ˈkɜː.nəl/", "lef-tén-ant kér-nel", "Oficial superior que comanda un batallón.", "Lieutenant colonel Diaz leads the airborne battalion.", "El teniente coronel Díaz lidera el batallón aerotransportado."),
    ("colonel", "coronel", "Military Ranks & Hierarchy", "noun", "/ˈkɜː.nəl/", "kér-nel", "Oficial superior que comanda un regimiento o brigada.", "The colonel addressed the assembled regimental staff.", "El coronel se dirigió al estado mayor regimental reunido."),
    ("brigadier general", "general de brigada", "Military Ranks & Hierarchy", "noun", "/ˌbrɪɡ.əˈdɪər ˈdʒen.ər.əl/", "brig-a-díer dchén-er-al", "Oficial general al mando de una brigada.", "The brigadier general inspected forward operating bases.", "El general de brigada inspeccionó las bases operativas avanzadas."),
    ("major general", "general de división", "Military Ranks & Hierarchy", "noun", "/ˌmeɪ.dʒə ˈdʒen.ər.əl/", "méi-dchor dchén-er-al", "Oficial general al mando de una división.", "Major general Alvarez approved the divisional war plan.", "El general de división Álvarez aprobó el plan de guerra divisional."),
    ("lieutenant general", "teniente general", "Military Ranks & Hierarchy", "noun", "/lefˌten.ənt ˈdʒen.ər.əl/", "lef-tén-ant dchén-er-al", "Oficial general de tres estrellas al mando de cuerpo.", "The lieutenant general serves on the joint chiefs staff.", "El teniente general presta servicio en el estado mayor conjunto."),
    ("general", "general de ejército", "Military Ranks & Hierarchy", "noun", "/ˈdʒen.ər.əl/", "dchén-er-al", "Máxima graduación militar ordinaria.", "The general briefed the civilian defense minister.", "El general informó al ministro de defensa civil."),
    ("fire team", "equipo de fuego", "Military Ranks & Hierarchy", "noun", "/ˈfaɪə tiːm/", "fáier tiim", "Grupo elemental de combate de 4 soldados.", "The fire team advanced under mutual cover.", "El equipo de fuego avanzó bajo cobertura mutua."),
    ("squad", "escuadra / grupo", "Military Ranks & Hierarchy", "noun", "/skwɒd/", "skuód", "Unidad militar básica de 8 a 10 combatientes.", "The rifle squad secured the hilltop perimeter.", "La escuadra de tiradores aseguró el perímetro de la colina."),
    ("platoon", "sección / pelotón", "Military Ranks & Hierarchy", "noun", "/pləˈtuːn/", "pla-túun", "Subunidad de 30 a 40 soldados al mando de un teniente.", "Third platoon held the crossroads firmly.", "La tercera sección sostuvo el cruce de caminos con firmeza."),
    ("company", "compañía", "Military Ranks & Hierarchy", "noun", "/ˈkʌm.pə.ni/", "kóm-pa-ni", "Unidad de 100 a 150 soldados al mando de un capitán.", "Bravo company assembled on the parade ground.", "La compañía Bravo formó en la plaza de armas."),
    ("battalion", "batallón", "Military Ranks & Hierarchy", "noun", "/bəˈtæl.jən/", "ba-tál-ion", "Unidad de 500 a 800 combatientes al mando de un teniente coronel.", "The 2nd Battalion deployed to the border sector.", "El 2.° Batallón se desplegó en el sector fronterizo."),
    ("regiment", "regimiento", "Military Ranks & Hierarchy", "noun", "/ˈredʒ.ɪ.mənt/", "rédch-i-ment", "Unidad militar histórica formada por varios batallones.", "The cavalry regiment paraded on independence day.", "El regimiento de caballería desfiló el día de la independencia."),
    ("brigade", "brigada", "Military Ranks & Hierarchy", "noun", "/brɪˈɡeɪd/", "bri-guéid", "Gran unidad táctica formada por varios batallones combinados.", "The mechanized brigade launched the counter-thrust.", "La brigada mecanizada lanzó la contraembestida."),
    ("division", "división", "Military Ranks & Hierarchy", "noun", "/dɪˈvɪʒ.ən/", "di-víshon", "Gran unidad militar de 10.000 a 15.000 efectivos.", "The infantry division mobilized for national defense.", "La división de infantería se movilizó para la defensa nacional."),
    ("corps", "cuerpo de ejército", "Military Ranks & Hierarchy", "noun", "/kɔːr/", "coor", "Gran agrupación militar de dos o más divisiones.", "The army corps commanded multi-national battle groups.", "El cuerpo de ejército mandó grupos de combate multinacionales.")
]

# Medical and First Aid
medical = [
    ("tourniquet", "torniquete táctico", "Medical & First Aid", "noun", "/ˈtʊə.nɪ.keɪ/", "tóor-ni-ket", "Banda para detener hemorragias masivas en extremidades.", "Apply a combat application tourniquet high and tight.", "Aplique un torniquete táctico alto y apretado."),
    ("pressure bandage", "vendaje de compresión (israelí)", "Medical & First Aid", "noun", "/ˈpreʃ.ər ˈbæn.dɪdʒ/", "présh-er bán-didch", "Vendaje compresivo estéril para heridas sangrantes.", "The combat medic placed a pressure bandage on the wound.", "El enfermero colocó un vendaje de compresión en la herida."),
    ("hemostatic gauze", "gasa hemostática", "Medical & First Aid", "noun", "/ˌhiː.məʊˈstæt.ɪk ɡɔːz/", "jii-móu-stát-ik goos", "Gasa con coagulante para taponar heridas profundas.", "Pack the wound cavity tightly with hemostatic gauze.", "Rellene bien la cavidad de la herida con gasa hemostática."),
    ("triage", "triaje / clasificación de heridos", "Medical & First Aid", "noun & verb", "/ˈtriː.ɑːʒ/", "tríi-aash", "Clasificación médica de víctimas según gravedad.", "Triage category Red receives immediate surgical attention.", "La categoría de triaje Rojo recibe atención quirúrgica inmediata."),
    ("medevac", "evacuación médica (MEDEVAC)", "Medical & First Aid", "noun & verb", "/ˈmed.ɪ.væk/", "méd-i-vak", "Evacuación médica en helicóptero o ambulancia.", "Request priority medevac for two litter patients.", "Soliciten medevac prioritario para dos pacientes en camilla."),
    ("casevac", "evacuación de bajas no medicalizada (CASEVAC)", "Medical & First Aid", "noun & verb", "/ˈkæs.ə.væk/", "kás-e-vak", "Evacuación rápida de heridos en vehículos de combate.", "Casevac was conducted using an armoured troop carrier.", "La evacuación de bajas se realizó usando un blindado."),
    ("stretcher", "camilla", "Medical & First Aid", "noun", "/ˈstretʃ.ər/", "stréch-er", "Dispositivo portátil para transportar heridos acostados.", "Four soldiers carried the wounded comrade on a stretcher.", "Cuatro soldados trasladaron al camarada herido en camilla."),
    ("splint", "férula", "Medical & First Aid", "noun & verb", "/splɪnt/", "splint", "Aparato rígido para inmovilizar huesos fracturados.", "Immobilize the fractured forearm with a padded splint.", "Inmovilice el antebrazo fracturado con una férula acolchada."),
    ("hypothermia", "hipotermia", "Medical & First Aid", "noun", "/ˌhaɪ.pəʊˈθɜː.mi.ə/", "jái-pou-zéer-mi-a", "Descenso peligroso de la temperatura corporal.", "Wrap trauma patients in thermal blankets to prevent hypothermia.", "Envuelva a los traumatizados en mantas térmicas para evitar la hipotermia."),
    ("resuscitation", "reanimación cardiopulmonar (RCP)", "Medical & First Aid", "noun", "/rɪˌsʌs.ɪˈteɪ.ʃən/", "ri-sas-i-téishon", "Maniobras para restaurar la respiración y el pulso.", "Medics initiated immediate CPR resuscitation.", "Los enfermeros iniciaron maniobras inmediatas de reanimación."),
    ("dehydration", "deshidratación", "Medical & First Aid", "noun", "/ˌdiː.haɪˈdreɪ.ʃən/", "dii-jai-dréishon", "Pérdida excesiva de agua y electrolitos del cuerpo.", "Drink water regularly during desert patrols to avoid dehydration.", "Beban agua con regularidad en patrullas desérticas para evitar la deshidratación."),
    ("first aid kit", "botiquín de primeros auxilios (IFAK)", "Medical & First Aid", "noun", "/ˌfɜːst ˈeɪd kɪt/", "féerst éid kit", "Estuche individual con material de primeros auxilios.", "Every soldier must carry an individual first aid kit on their belt.", "Cada soldado debe llevar un botiquín individual en su cinturón.")
]

# UN Peacekeeping and Diplomacy
un_peace = [
    ("blue helmet", "casco azul (ONU)", "UN Peacekeeping", "noun", "/bluː ˈhel.mɪt/", "bluu jél-mit", "Soldado de las misiones de mantenimiento de la paz de la ONU.", "Blue helmets monitored the demilitarized buffer zone.", "Los cascos azules vigilaron la zona de amortiguación desmilitarizada."),
    ("peacekeeper", "fuerza de paz / pacificador", "UN Peacekeeping", "noun", "/ˈpiːsˌkiː.pər/", "píis-kii-per", "Efectivo desplegado para mantener o consolidar la paz.", "Peacekeepers maintained round-the-clock observation posts.", "Las fuerzas de paz mantuvieron puestos de observación las 24 horas."),
    ("buffer zone", "zona de amortiguamiento / colchón", "UN Peacekeeping", "noun", "/ˈbʌf.ər zəʊn/", "báf-er zóun", "Franja neutral que separa fuerzas beligerantes.", "Armed forces are strictly prohibited from entering the buffer zone.", "Las fuerzas armadas tienen prohibido entrar en la zona de amortiguamiento."),
    ("demilitarized zone", "zona desmilitarizada (DMZ)", "UN Peacekeeping", "noun", "/diːˈmɪl.ɪ.tər.aɪzd zəʊn/", "dii-míl-i-ta-raisd zóun", "Área donde se prohíben tropas y armas según tratado.", "Both belligerents withdrew beyond the demilitarized zone.", "Ambos beligerantes se replegaron más allá de la zona desmilitarizada."),
    ("ceasefire agreement", "acuerdo de alto el fuego", "UN Peacekeeping", "noun", "/ˈsiːs.faɪər əˌɡriː.mənt/", "síis-fáier a-gríi-ment", "Pacto formal que detiene las hostilidades armadas.", "Diplomats drafted a lasting ceasefire agreement.", "Los diplomáticos redactaron un acuerdo duradero de alto el fuego."),
    ("disarmament", "desarme", "UN Peacekeeping", "noun", "/dɪˈsɑː.mə.mənt/", "dis-áar-ma-ment", "Reducción o destrucción controlada de armas y pertrechos.", "The UN mission oversaw the voluntary disarmament of militias.", "La misión de la ONU supervisó el desarme voluntario de las milicias."),
    ("demobilization", "desmovilización", "UN Peacekeeping", "noun", "/diːˌməʊ.bəl.aɪˈzeɪ.ʃən/", "dii-mou-bi-lai-zéishon", "Disolución oficial de unidades militares o guerrilleras.", "Demobilization centers provided vocational training to former fighters.", "Los centros de desmovilización brindaron capacitación laboral a excombatientes."),
    ("humanitarian aid", "ayuda humanitaria", "UN Peacekeeping", "noun", "/hjuːˌmæn.ɪˈteə.ri.ən eɪd/", "jiu-man-i-téa-rian éid", "Asistencia de comida, medicina y cobijo para víctimas.", "Convoys delivered essential humanitarian aid to cut-off villages.", "Los convoyes entregaron ayuda humanitaria esencial a aldeas aisladas."),
    ("refugee camp", "campo de refugiados", "UN Peacekeeping", "noun", "/ˌref.jʊˈdʒiː kæmp/", "ref-iu-dchíi camp", "Instalación temporal para personas que huyen de guerras.", "Peacekeepers provided armed perimeter security around the refugee camp.", "Las fuerzas de paz brindaron seguridad perimétrica armada al campo de refugiados."),
    ("rules of engagement", "reglas de enfrentamiento (ROE)", "UN Peacekeeping", "noun", "/ruːlz əv ɪnˈɡeɪdʒ.mənt/", "ruuls ov in-guéidch-ment", "Directivas operacionales de uso gradual de la fuerza.", "Under current ROE, lethal force is authorized solely in self-defense.", "Bajo las actuales ROE, la fuerza letal se autoriza solo en legítima defensa.")
]

# General everyday vocabulary + connectors + STANAG 6001 terms
general_words = [
    # Verbs
    ("brief", "instruir / dar instrucciones breves", "Military Routine", "verb", "/briːf/", "bríif", "Dar información y órdenes antes de una misión.", "The officer will brief the squad before departure.", "El oficial instruirá a la escuadra antes de partir."),
    ("debrief", "interrogar / evaluar misión concluida", "Military Routine", "verb", "/ˌdiːˈbriːf/", "dii-bríif", "Reunir datos de los participantes tras la misión.", "Intelligence officers debriefed the return patrol.", "Los oficiales de inteligencia interrogaron a la patrulla de regreso."),
    ("salute", "saludar militarmente / saludo", "Military Routine", "verb & noun", "/səˈluːt/", "sa-lúut", "Gesto formal de respeto militar con la mano a la sien.", "Soldiers must salute commissioned officers.", "Los soldados deben saludar militarmente a los oficiales."),
    ("muster", "pasar revista / pasar lista", "Military Routine", "verb & noun", "/ˈmʌs.tər/", "más-ter", "Reunir tropas para verificación o inspección.", "Muster on the quadrangle at 0630 hours.", "Formen revista en el patio a las 0630 horas."),
    ("parade", "desfile / formación militar", "Military Routine", "noun & verb", "/pəˈreɪd/", "pa-réid", "Formación o marcha militar reglamentaria.", "The regiment held a parade for the national holiday.", "El regimiento celebró un desfile por la fiesta nacional."),
    ("barracks", "cuartel / alojamiento de tropa", "Military Routine", "noun", "/ˈbær.əks/", "bá-raks", "Edificio militar donde viven y duermen soldados.", "Recruits clean their barracks every morning.", "Los reclutas limpian su cuartel cada mañana."),
    ("guard duty", "servicio de guardia / imaginaria", "Military Routine", "noun", "/ɡɑːd ˈdʒuː.ti/", "gard dchúu-ti", "Servicio de vigilancia y protección de instalaciones.", "Corporal Lopez was assigned to overnight guard duty.", "El cabo López fue asignado a servicio de guardia nocturna."),
    ("sentry", "centinela", "Military Routine", "noun", "/ˈsen.tri/", "sén-tri", "Soldado apostado en un puesto de guardia.", "The sentry challenged anyone approaching the main bunker.", "El centinela dio el alto a quienquiera que se acercase al búnker."),
    ("curfew", "toque de queda", "Military Routine", "noun", "/ˈkɜː.fjuː/", "kér-fiu", "Orden de prohibición de circular en horas de la noche.", "A strict curfew was imposed from 2100 to 0600.", "Se impuso un estricto toque de queda de 2100 a 0600."),
    ("billet", "alojamiento militar / acantonar", "Military Routine", "noun & verb", "/ˈbɪl.ɪt/", "bíl-it", "Lugar asignado a tropas para hospedarse.", "Troops were billeted in regional school halls.", "Las tropas fueron acantonadas en salones escolares regionales.")
]

# Let's populate the initial lists
for w in tactical:
    add(w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8])
for w in weapons:
    add(w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8])
for w in radio:
    add(w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8])
for w in ranks:
    add(w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8])
for w in medical:
    add(w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8])
for w in un_peace:
    add(w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8])
for w in general_words:
    add(w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], w[8])

print(f"Current count: {len(entries)}")
